// <auto-generated />
using System;
using CarCollectionApp.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace CarCollectionApp.Migrations
{
    [DbContext(typeof(CarCollectionContext))]
    partial class CarCollectionContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.3")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("CarCollectionApp.Models.Brand", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Country")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Brands");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Country = "Germany",
                            Name = "BMW"
                        },
                        new
                        {
                            Id = 2,
                            Country = "Germany",
                            Name = "Audi"
                        },
                        new
                        {
                            Id = 3,
                            Country = "USA",
                            Name = "Chevrolet"
                        },
                        new
                        {
                            Id = 4,
                            Country = "Italy",
                            Name = "Ferrari"
                        },
                        new
                        {
                            Id = 5,
                            Country = "Italy",
                            Name = "Lamborghini"
                        },
                        new
                        {
                            Id = 6,
                            Country = "UK",
                            Name = "McLaren"
                        },
                        new
                        {
                            Id = 7,
                            Country = "Germany",
                            Name = "Mercedes-Benz"
                        },
                        new
                        {
                            Id = 8,
                            Country = "USA",
                            Name = "Ford"
                        },
                        new
                        {
                            Id = 9,
                            Country = "Germany",
                            Name = "Porsche"
                        },
                        new
                        {
                            Id = 10,
                            Country = "USA",
                            Name = "Tesla"
                        });
                });

            modelBuilder.Entity("CarCollectionApp.Models.Car", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("BrandId")
                        .HasColumnType("int");

                    b.Property<int>("CategoryId")
                        .HasColumnType("int");

                    b.Property<int>("DealerId")
                        .HasColumnType("int");

                    b.Property<string>("Engine")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FuelType")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Horsepower")
                        .HasColumnType("int");

                    b.Property<string>("ImagePath")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Model")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("Price")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("Transmission")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Year")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("BrandId");

                    b.HasIndex("CategoryId");

                    b.HasIndex("DealerId");

                    b.ToTable("Cars");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            BrandId = 1,
                            CategoryId = 1,
                            DealerId = 1,
                            Engine = "3.0L Twin-Turbo I6",
                            FuelType = "Petrol",
                            Horsepower = 503,
                            ImagePath = "bmw-m4.jpg",
                            Model = "BMW M4",
                            Price = 85000m,
                            Transmission = "Automatic",
                            Year = 2023
                        },
                        new
                        {
                            Id = 2,
                            BrandId = 2,
                            CategoryId = 3,
                            DealerId = 1,
                            Engine = "5.2L V10",
                            FuelType = "Petrol",
                            Horsepower = 562,
                            ImagePath = "audi-r8.jpg",
                            Model = "Audi R8",
                            Price = 145000m,
                            Transmission = "Automatic",
                            Year = 2022
                        },
                        new
                        {
                            Id = 3,
                            BrandId = 3,
                            CategoryId = 1,
                            DealerId = 1,
                            Engine = "6.2L V8",
                            FuelType = "Petrol",
                            Horsepower = 495,
                            ImagePath = "corvette-c8.jpg",
                            Model = "Corvette C8",
                            Price = 67000m,
                            Transmission = "Automatic",
                            Year = 2022
                        },
                        new
                        {
                            Id = 4,
                            BrandId = 4,
                            CategoryId = 3,
                            DealerId = 1,
                            Engine = "3.9L Twin-Turbo V8",
                            FuelType = "Petrol",
                            Horsepower = 710,
                            ImagePath = "ferrari-f8.jpg",
                            Model = "Ferrari F8",
                            Price = 276000m,
                            Transmission = "Automatic",
                            Year = 2023
                        },
                        new
                        {
                            Id = 5,
                            BrandId = 5,
                            CategoryId = 3,
                            DealerId = 1,
                            Engine = "5.2L V10",
                            FuelType = "Petrol",
                            Horsepower = 631,
                            ImagePath = "lamborghini-huracan.jpg",
                            Model = "Lamborghini Huracan",
                            Price = 261000m,
                            Transmission = "Automatic",
                            Year = 2022
                        },
                        new
                        {
                            Id = 6,
                            BrandId = 6,
                            CategoryId = 3,
                            DealerId = 1,
                            Engine = "4.0L Twin-Turbo V8",
                            FuelType = "Petrol",
                            Horsepower = 710,
                            ImagePath = "mclaren-720s.jpg",
                            Model = "McLaren 720S",
                            Price = 299000m,
                            Transmission = "Automatic",
                            Year = 2023
                        },
                        new
                        {
                            Id = 7,
                            BrandId = 7,
                            CategoryId = 1,
                            DealerId = 1,
                            Engine = "4.0L V8 Biturbo",
                            FuelType = "Petrol",
                            Horsepower = 523,
                            ImagePath = "mercedes-amg-gt.jpg",
                            Model = "Mercedes-AMG GT",
                            Price = 118000m,
                            Transmission = "Automatic",
                            Year = 2023
                        },
                        new
                        {
                            Id = 8,
                            BrandId = 8,
                            CategoryId = 1,
                            DealerId = 1,
                            Engine = "5.0L V8",
                            FuelType = "Petrol",
                            Horsepower = 450,
                            ImagePath = "mustang-gt.jpg",
                            Model = "Ford Mustang GT",
                            Price = 55000m,
                            Transmission = "Manual",
                            Year = 2022
                        },
                        new
                        {
                            Id = 9,
                            BrandId = 9,
                            CategoryId = 1,
                            DealerId = 1,
                            Engine = "3.0L Twin-Turbo Flat-6",
                            FuelType = "Petrol",
                            Horsepower = 443,
                            ImagePath = "porsche-911.jpg",
                            Model = "Porsche 911",
                            Price = 110000m,
                            Transmission = "Automatic",
                            Year = 2023
                        },
                        new
                        {
                            Id = 10,
                            BrandId = 10,
                            CategoryId = 2,
                            DealerId = 1,
                            Engine = "Dual Motor Electric",
                            FuelType = "Electric",
                            Horsepower = 1020,
                            ImagePath = "tesla-model-s.jpg",
                            Model = "Tesla Model S",
                            Price = 104000m,
                            Transmission = "Automatic",
                            Year = 2023
                        });
                });

            modelBuilder.Entity("CarCollectionApp.Models.Category", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("DoorCount")
                        .HasColumnType("int");

                    b.Property<int>("Seats")
                        .HasColumnType("int");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Categories");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            DoorCount = 2,
                            Seats = 2,
                            Type = "Coupe"
                        },
                        new
                        {
                            Id = 2,
                            DoorCount = 4,
                            Seats = 5,
                            Type = "Sedan"
                        },
                        new
                        {
                            Id = 3,
                            DoorCount = 2,
                            Seats = 2,
                            Type = "Supercar"
                        });
                });

            modelBuilder.Entity("CarCollectionApp.Models.Dealer", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("City")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Country")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Phone")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Dealers");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            City = "Los Angeles",
                            Country = "USA",
                            Email = "contact@calidreamcars.com",
                            Name = "California Dream Cars",
                            Phone = "323-555-9876"
                        });
                });

            modelBuilder.Entity("CarCollectionApp.Models.Review", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("CarId")
                        .HasColumnType("int");

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("Created")
                        .HasColumnType("datetime2");

                    b.Property<int>("Rating")
                        .HasColumnType("int");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("CarId");

                    b.HasIndex("UserId");

                    b.ToTable("Reviews");
                });

            modelBuilder.Entity("CarCollectionApp.Models.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("JoinDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("CarCollectionApp.Models.Car", b =>
                {
                    b.HasOne("CarCollectionApp.Models.Brand", "Brand")
                        .WithMany("Cars")
                        .HasForeignKey("BrandId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("CarCollectionApp.Models.Category", "Category")
                        .WithMany("Cars")
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("CarCollectionApp.Models.Dealer", "Dealer")
                        .WithMany("Cars")
                        .HasForeignKey("DealerId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Brand");

                    b.Navigation("Category");

                    b.Navigation("Dealer");
                });

            modelBuilder.Entity("CarCollectionApp.Models.Review", b =>
                {
                    b.HasOne("CarCollectionApp.Models.Car", "Car")
                        .WithMany("Reviews")
                        .HasForeignKey("CarId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("CarCollectionApp.Models.User", "User")
                        .WithMany("Reviews")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Car");

                    b.Navigation("User");
                });

            modelBuilder.Entity("CarCollectionApp.Models.Brand", b =>
                {
                    b.Navigation("Cars");
                });

            modelBuilder.Entity("CarCollectionApp.Models.Car", b =>
                {
                    b.Navigation("Reviews");
                });

            modelBuilder.Entity("CarCollectionApp.Models.Category", b =>
                {
                    b.Navigation("Cars");
                });

            modelBuilder.Entity("CarCollectionApp.Models.Dealer", b =>
                {
                    b.Navigation("Cars");
                });

            modelBuilder.Entity("CarCollectionApp.Models.User", b =>
                {
                    b.Navigation("Reviews");
                });
#pragma warning restore 612, 618
        }
    }
}
